version: 2.1

jobs:
  build:
    docker:
      # Use a Maven image with Java 11
      - image: cimg/openjdk:11.0
    working_directory: ~/project
    steps:
      # Checkout the code
      - checkout

      # Cache Maven dependencies
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-

      # Run Maven build
      - run:
          name: Build with Maven
          command: mvn clean package --file pom.xml

      # Save Maven dependencies for caching
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}

      # Verify build output
      - run:
          name: Verify Build Output
          command: |
            ls -l target/jpackage-input/downloader-1.0-SNAPSHOT.jar
            ls -l target/*.tar.gz

      # Store the tar.gz artifact
      - store_artifacts:
          path: target
          destination: artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build