name: Build Installers
on: [push]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Debug Input Directory
        run: ls -l target/jpackage-input || echo "Directory not found"
      - name: Build macOS Installer
        run: mvn clean package -Pjpackage-macos -X
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: target/jpackage/macos/*.dmg
          if-no-files-found: error
  build-linux-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Install Debian Tools
        run: sudo apt-get update && sudo apt-get install -y fakeroot dpkg binutils libc6-dev
      - name: Debug Input Directory
        run: ls -l target/jpackage-input || echo "Directory not found"
      - name: Build Linux DEB Installer
        run: mvn clean package -Pjpackage-linux-deb -X
      - name: Upload Linux DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-installer
          path: target/jpackage/linux-deb/*.deb
          if-no-files-found: error
  build-linux-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Install RPM Tools
        run: sudo apt-get update && sudo apt-get install -y rpm
      - name: Debug Input Directory
        run: ls -l target/jpackage-input || echo "Directory not found"
      - name: Build Linux RPM Installer
        run: mvn clean package -Pjpackage-linux-rpm -X
      - name: Upload Linux RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-installer
          path: target/jpackage/linux-rpm/*.rpm
          if-no-files-found: error
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Add WiX to PATH
        run: echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" >> $GITHUB_PATH
        shell: bash
      - name: Verify WiX Tools
        run: candle.exe -v
        shell: cmd
      - name: Create Input Directory
        run: mkdir target\jpackage-input
        shell: cmd
      - name: Debug Compilation Output
        run: dir target
        shell: cmd
      - name: Debug Input Directory
        run: dir target\jpackage-input
        shell: cmd
      - name: Build Windows MSI Installer
        run: mvn clean package -Pjpackage-windows-msi -X
        shell: cmd
      - name: Upload Windows MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer
          path: target/jpackage/windows-msi/*.msi
          if-no-files-found: error